version: '3'

services:
  basewebapi:
    build: 
      context: .
      dockerfile: Dockerfile
    image: basewebapi-docker
    container_name: basewebapi
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
